# Imported sprite strips: name = anchor x, anchor y (the feet, in pixels of one frame), frame count. Written by the art prep tool.
barrel_city=8,27,1
barrel_forest=11,27,1
barrel_lab=8,26,1
city_boss=38,80,1
city_brute=22,40,1
city_grunt=15,31,1
city_runner=13,24,1
city_shooter=18,32,1
crate_city=13,27,1
crate_forest=13,27,1
crate_lab=13,27,1
forest_boss=36,82,1
forest_brute=19,47,1
forest_grunt=13,33,1
forest_runner=18,25,1
forest_shooter=17,32,1
lab_boss=32,76,1
lab_brute=26,54,1
lab_grunt=16,28,1
lab_runner=13,26,1
lab_shooter=16,34,1
landmark_boulder=21,32,1
landmark_bush=15,27,1
landmark_oak=30,79,1
landmark_stump=19,28,1
run_chest_boss=15,33,1
run_chest_elite=16,28,1
shade=15,35,1
